baseURL: https://weneves.netlify.app
languageCode: en-us
theme: aafu
params:
  aboutme:
    description: Site dedicado à análise de dados estatísticos com ênfase em ecologia marinha utilizando a linguagem R.
    icon: fas fa-user
    title: Sobre
  author: Wesley Neves
  copyright: short copyright message
  description: Website title
  education:
    icon: fas fa-graduation-cap
    list:
      - college: Universidade Federal de Pernambuco
        dates: 2021 - 2023
        degree: M.S. em Biologia Animal (PPGBA - UFPE)
        thesis_title: 'Caracterização da Diversidade Funcional de Macrobentos e do Tipo e Estado de Cinco Prais do Litoral de Pernambuco.'
        thesis_url: '#'
      - college: Universidade Federal de Pernambuco
        dates: 2016 - 2021
        degree: B.S. em Ciências Biológicas/Ciências Ambientais
        thesis_title: 'Curvas de Acumulação de Diversidade Efetiva em Comunidades de Macrobentos da Praia de Tamandaré.'
        thesis_url: '#'
    title: Formação
  experience:
    icon: fas fa-briefcase
    list:
      - company: Pré-Vestibular InovAÇÃO
        dates: 2019 - *Present*
        details: Ministrei aulas nos diversos temas das Ciências da Natureza, requeridos para o Exame Nacional do Ensino Médio - ENEM.
        position: Job Title
      - company: Curso de Curta Duração - Ecologia Prática_R.
        dates: 2020 - *Present*
        position: Job Title
        url: '#'
    title: Experiências
  favicons:
    metas: "        <link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"apple-touch-icon.png\">\n
      \       <link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"favicon-32x32.png\">\n
      \       <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"favicon-16x16.png\">\n
      \       <link rel=\"manifest\" href=\"site.webmanifest\">\n        <link rel=\"mask-icon\"
      href=\"safari-pinned-tab.svg\" color=\"#252627\">\n        <link rel=\"shortcut
      icon\" href=\"favicon.ico\">\n        "
    use: yes
  hobby:
    icon: fas fa-gamepad
    list:
      - hobby: Cooking
      - hobby: Hiking
      - hobby: Baking
    title: Hobbies
  profile:
    location: City Name, ST
    name: First Last, Abbr.
    photo: profile.jpg
    tagline: Title
  project:
    icon: fas fa-project-diagram
    list:
      - description: Description of the project
        title: Project 1
        url: '#'
      - description: Description of the project
        title: Project 2
        url: '#'
      - description: Description of the project
        title: Project 3
        url: '#'
      - description: Description of the project
        title: Project 4
        url: '#'
    title: Projects
  publication:
    format:
      - date
      - authors
      - title
      - journal
    icon: fas fa-book
    list:
      - authors: F Last, F Second, P secondary
        date: '2018'
        journal: Journal of Field 52 (16), 9033-9044
        title: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
          tempor incididunt ut labore et dolore magna aliqua.
        type: Journal Articles
        url: '#'
      - authors: F Last, F Second, P secondary
        date: '2018'
        journal: Journal of Field 52 (16), 9033-9044
        title: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
          tempor incididunt ut labore et dolore magna aliqua.
        type: Journal Articles
        url: '#'
      - authors: F Last, F Second, P secondary
        date: '2018'
        journal: Journal of Field 52 (16), 9033-9044
        title: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
          tempor incididunt ut labore et dolore magna aliqua.
        type: Proceedings
        url: '#'
    title: Publications
    types:
      - Journal Articles
      - Proceedings
  showInAccordion:
    - expand: yes
      item: aboutme
    - item: experience
    - item: education
    - item: publication
    - item: project
    - item: skill
    - item: hobby
  skill:
    icon: fas fa-cogs
    list:
      - skill: Skill 1, Skill 2
        skillrating: 90
      - skill: Skill 3
        skillrating: 80
      - skill: Skill 4
        skillrating: 50
    panelId: skill-panel
    title: Skills
  social:
    list:
      - icon: fab fa-linkedin-in
        title: LinkedIn
        url: '#'
      - icon: fab fa-stack-overflow
        title: StackOverflow
        url: '#'
      - icon: fab fa-github
        title: GitHub
        url: '#'
      - icon: fab fa-twitter
        title: Twitter
        url: '#'
      - icon: fab fa-orcid
        title: Orcid
        url: '#'
      - icon: ai ai-google-scholar
        title: Google Scholar
        url: '#'
      - icon: fab fa-researchgate
        title: ResearchGate
        url: '#'
    title: Links
  theme:
    mainTheme: ocean
    showAttribute: yes
    singlePage: no
  title: Aafu theme
