baseURL: https://weneves.netlify.app
languageCode: en-us
theme: aafu
params:
  aboutme:
    description: Site dedicado à análise de dados estatísticos com ênfase em ecologia marinha utilizando a linguagem R.
    icon: fas fa-user
    title: Sobre
  author: Wesley Neves
  copyright: Green Vibes Only
  description: Website title
  education:
    icon: fas fa-graduation-cap
    list:
      - college: Universidade Federal de Pernambuco
        dates: 2021 - 2023
        degree: M.S. em Biologia Animal (PPGBA - UFPE)
        thesis_title: 'Caracterização da Diversidade Funcional de Macrobentos e do Tipo e Estado de Cinco Prais do Litoral de Pernambuco.'
        thesis_url: '#'
      - college: Universidade Federal de Pernambuco
        dates: 2016 - 2021
        degree: B.S. em Ciências Biológicas/Ciências Ambientais
        thesis_title: 'Curvas de Acumulação de Diversidade Efetiva em Comunidades de Macrobentos da Praia de Tamandaré.'
        thesis_url: '#'
    title: Formação
  experience:
    icon: fas fa-briefcase
    list:
      - company: Pré-Vestibular InovAÇÃO
        dates: 2019 - *Present*
        details: Ministrei aulas nos diversos temas das Ciências da Natureza, requeridos para o Exame Nacional do Ensino Médio - ENEM.
        position: Professor de Biologia e Meio Ambiente
      - company: Curso de Curta Duração - Ecologia Prática_R.
        dates: 2020 - *Present*
        position: Professor Ecologia Prática
        url: '#'
    title: Experiências
  favicons:
    metas: "        <link rel=\"apple-touch-icon\" sizes=\"180x180\" href=\"apple-touch-icon.png\">\n
      \       <link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"favicon-32x32.png\">\n
      \       <link rel=\"icon\" type=\"image/png\" sizes=\"16x16\" href=\"favicon-16x16.png\">\n
      \       <link rel=\"manifest\" href=\"site.webmanifest\">\n        <link rel=\"mask-icon\"
      href=\"safari-pinned-tab.svg\" color=\"#252627\">\n        <link rel=\"shortcut
      icon\" href=\"favicon.ico\">\n        "
    use: yes
  hobby:
    icon: fas fa-gamepad
    list:
      - hobby: Kalimba
      - hobby: Desenhar
      - hobby: Ler
    title: Hobbies
  profile:
    location: Recife, PE
    name: Wesley, Neves.
    photo: profile.jpg
    tagline: 
  project:
    icon: fas fa-project-diagram
    list:
      - description: Nesse curso abordaremos inteiramente a Ecologia Matemática e suas vertentes (Estatística Ecológica, Modelagem Ecológica e Ecologia Numérica). Todas as abordagens estão aplicadas ao programa R, utilizando a interface RStudio.
        title: Curso Ecologia Prática no Programa R
        url: '/blog/curso_eco.r/sumario/'
    title: Projetos
  publication:
    format:
      - date
      - authors
      - title
      - journal
    icon: fas fa-book
    list:
      - authors: Em Construção
        date: '---'
        journal: ...
        title: ...
          ....
        type: ---
        url: '#'
      - authors: Em Construção
        date: '---'
        journal: ...
        title: ...
          ....
        type: ---
        url: '#'
      - authors: Em Construção
        date: '---'
        journal: ...
        title: ...
          ....
        type: ----
        url: '#'
    title: Leitura
    types:
      - Journal Articles
      - Proceedings
  showInAccordion:
    - expand: yes
      item: aboutme
    - item: skill
    - item: education
    - item: experience
    - item: project 
    - item: publication
    - item: hobby
  skill:
    icon: fas fa-cogs
    list:
      - skill: Programa R
        skillrating: 90
      - skill: Leitura
        skillrating: 100 
      - skill: Estatística
        skillrating: 90
    panelId: skill-panel
    title: Interesses
  social:
    list:
      - icon: fab fa-facebook-square
        title: Facebook
        url: 'https://www.facebook.com/wesley.neves.923171'
      - icon: fab fa-linkedin-in
        title: LinkedIn
        url: 'https://www.linkedin.com/in/wesley-neves-750052206/'
      - icon: fab fa-stack-overflow
        title: StackOverflow
        url: '#'
      - icon: fab fa-github
        title: GitHub
        url: 'https://github.com/wesneves'
      - icon: fab fa-twitter
        title: Twitter
        url: '#'
      - icon: fab fa-orcid
        title: Orcid
        url: '#'
      - icon: ai ai-google-scholar
        title: Google Scholar
        url: '#'
      - icon: fab fa-researchgate
        title: ResearchGate
        url: 'https://www.researchgate.net/profile/Wesley-Neves-2'
    title: Links
  theme:
    mainTheme: light
    showAttribute: no
    singlePage: no
  title: weneves
